# Generated by Django 5.2.7 on 2025-11-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacysystem', '0002_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('cod', models.CharField(max_length=50, unique=True)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
